
genkais = [
    "Aidens-Son-Mud",
    "Aizden",
    "Akuma",
    "Alphirama-Shizen",
    "Apol-Sand"
    "Apollo-Sand",
    "Arahaki-Jokei",
    "Ashen-Storm",
    "Ashura Shizen",
    "Azarashi",
    "Azim-Senko",
    "Bankai-Akuma",
    "Bankai-Inferno",
    "Black Lightning",
    "Blood",
    "Boil",
    "Bolt",
    "Borumaki Gaiden",
    "Borumaki",
    "Bruce Kenichi",
    "Bubble",
    "Clay",
    "Cobra",
    "Code Gaiden",
    "Crystal",
    "Dangan",
    "Deva Rengoku",
    "Dio Senko",
    "Dokei",
    "Doku Tengoku",
    "Dust",
    "Eastwood Korashi",
    "Emerald",
    "Eternal",
    "Explosion",
    "Fizz",
    "Forged Rengoku",
    "Frost",
    "Fume",
    "Getsuga",
    "Ghost Korashi",
    "Giovanni Shizen",
    "Glacier",
    "Gold Sand",
    "Hair",
    "Headless",
    "Ice",
    "Indra Akuma",
    "Inferno",
    "Ink",
    "Jayramaki",
    "Jinshiki",
    "Jokei",
    "Kagoku",
    "Kagoku",
    "Kaijin",
    "Kamaki Akuma",
    "Kamaki",
    "Kenichi",
    "Kerada",
    "Kokotsu",
    "Koncho",
    "Koncho",
    "Lava",
    "Light Jokei",
    "Magma",
    "Mecha Spirit",
    "Menza",
    "Minakami",
    "Minakaze",
    "Mud",
    "Narumaki",
    "Nectar",
    "Octo-Ink",
    "Odin Saberu",
    "Okami",
    "Paper",
    "Pika Senko",
    "Powder",
    "Ragnar",
    "Raiden Saberu",
    "Raion Akuma",
    "Raion Gaiden",
    "Raion Rengoku",
    "Rengoku",
    "Renshiki",
    "Riser Akuma",
    "Rykan Shizen",
    "Ryuji Kenichi",
    "Saberu",
    "Sand",
    "Sarachia Akuma",
    "Satori Akuma",
    "Satori Rengoku",
    "Scorch",
    "Sean Kerada",
    "Seishin",
    "Sengoku",
    "Senko",
    "Shado",
    "Shindai Akuma",
    "Shindai Rengoku",
    "Shiro Glacier",
    "Shiver Akuma",
    "Shizen",
    "Six Path Narumaki",
    "Smoke",
    "Snakeman",
    "Sound",
    "Storm",
    "Strange",
    "Surge",
    "Tengoku",
    "Tetsuo Kaijin",
    "Tsunami",
    "Typhoon",
    "Vanhelsing",
    "Vengeance",
    "Vine",
    "Wanziame",
    "Web",
    "Wood",
    "Xeno Dokei",
]



elementos = [
    "Acid",
    "Cement",
    "Chaos",
    "Combustion",
    "Earth",
    "Fire",
    "Gale",
    "Lightning",
    "Pyro"
    "Shiver",
    "Water",
    "Wind",
    "Yin",
]


kenjutsus = [
    "Fire",
    "Mist",
    "Moon",
    "Shiver"
    "Sound",
    "Sun",
    "Thunder",
    "Water",
    "Wind",
]
